### PR TITLE
Cinnamenu@json : Update da.po

### PR DESCRIPTION
**Pull request by fusentast**
Danish translation for Version 4.2.10

@fredcw

### CODE REVIEW

**Comment by fredcw** [comment]
@fusentast Thanks, but slight problem. You've accidentally put it in the wrong directory ;)

**Comment by fusentast** [comment]
Sorry what exact directory is it supposed to go in?

**Comment by fredcw** [comment]
@fusentast cinnamon-spices-applets/Cinnamenu@json/po/da.po

**Comment by fredcw** [comment]
@fusentast I just noticed that you didn't do the PR at linuxmint yet. If you want you can just email the file to me if it's easier. If you want to do a PR, these are the steps I would take:

1) You've already cloned /linuxmint/cinnamon-spices-applets as /fusentast/cinnamon-spices-applets so you should delete this clone and start again fresh just in case.

To delete your clone: go to https://github.com/fusentast/cinnamon-spices-applets and click on "settings" (near the top right). Go to the bottom of the settings page and click "delete this repository" - then confirm that you're deleting "/fusentast/cinnamon-spices-applets".

2) Go back to /linuxmint/cinnamon-spices-applets (https://github.com/linuxmint/cinnamon-spices-applets) and click on "fork" (top right) to create a new clone called /fusentast/cinnamon-spices-applets

3) Update da.po into your cloned repository: navigate to https://github.com/fusentast/cinnamon-spices-applets/tree/master/Cinnamenu%40json/files/Cinnamenu%40json/po and upload your new version by either clicking on "Add file" -> "upload files" or just drag and drop the file onto the web page.

Click on "commit changes" at the bottom.

4)Create a PR to merge your changes with linuxmint: Go to https://github.com/fusentast/cinnamon-spices-applets and click on "pull request" (near top right) and on next page "create pull request". Add title and comment and click "create pull request" again. Now when you go to https://github.com/linuxmint/cinnamon-spices-applets and click on "pull requests", you should see your PR on the list.

5) After your PR has been merged by linuxmint, you can then safely delete your clone /fusentast/cinnamon-spices-applets at https://github.com/fusentast/cinnamon-spices-applets again.

Yes, it's rather complicated just to update a translation so it's fine to email it to me if that easier. Thanks.

**Comment by fredcw** [comment]
@fusentast I've downloaded your new version of da.po now anyway so I can just add it to my next PR.

**Comment by fusentast** [comment]
That ok.
I actually tried to do as you suggested in another thread here:

https://github.com/fusentast/cinnamon-spices-applets/commit/5a091800d300d6ee6aefae5d80a07cf27924b641

I guess that's not the right way too.
PR's at Github might just be too geeky for me - sorry I meant advanced.
I'll have a hard long look at what you wrote over the weekend, maybe.

Then I'll decide if I want to bother or just mail you the da.po files in the future.
Thanks

**Pull request closed without merging**
